[versions]
version-name = "0.27.0"
version-code = "37"

compile-sdk = "36"
target-sdk = "36"
min-sdk = "26"
accompanist = "0.35.0-alpha"
firebase-appdistribution-gradle = "5.0.0"
firebase-crashlytics-gradle = "3.0.2"
kotlin = "2.3.0"
ksp = "2.3.2"
android-tools = "31.13.2"
# android-tools and agp should be updated together
agp = "8.13.2"
core-ktx = "1.17.0"
coil = "3.3.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.3.0"
androidx-tracing = "1.3.0"
androidx-browser = "1.9.0"
lifecycle-runtime-ktx = "2.10.0"
activity-compose = "1.11.0"
start-up = "1.2.0"
kotlinx-datetime = "0.7.1"
ktlint-cli = "1.8.0"
secrets = "2.0.1"
navigation-compose = "2.9.6"
crashlytics = "19.4.4"
detekt = "1.23.6"

# Internal Database
sqldelight = "2.2.1"
datastore = '1.2.0'

# Multithreading
kotlinx-coroutines = '1.10.2'

# Network & Serialization
ktor = "3.3.3"
kotlinx-serialization = "1.9.0"
kotlinx-io = "0.8.2"

# Depedency Injection
koin = "4.1.1"

# Compose Multiplatform
compose-multiplatform = "1.10.0"
compose-multiplatform-adaptive = "1.2.0"
compose-multiplatform-material3 = "1.10.0-alpha05"
compose-material-icons-extended = "1.7.3"
lifecycle-multiplatform = "2.10.0-alpha07"
compose-navigation = "2.9.1"
compose-shimmer = "1.3.3"
compose-colorpicker = "1.1.3"
materialkolor = "4.1.0"

# Misc
napier = "2.7.1"
android-youtube-player = "13.0.0"
cryptography = "0.5.0"

# Testing
kover = "0.9.4"
screenshot = "0.0.1-alpha11"
androidx-test = "1.7.0"
truth = "1.4.5"
turbine = "1.2.1"
kotest = "6.0.5"

# UI
robolectric = "4.16"
androidx-compose-ui-test = "1.10.1"
ui-automator = "2.3.0"

# Mockers
mockito = "5.21.0"
mockito-kotlin = "6.1.0"

[libraries]

# Android X
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "start-up" }
androidx-tracing-ktx = { group = "androidx.tracing", name = "tracing-ktx", version.ref = "androidx-tracing" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidx-browser" }

kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }

# Jetpack Compose
compose-multiplatform-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-multiplatform-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-multiplatform-material3 = { module = " org.jetbrains.compose.material3:material3", version.ref = "compose-multiplatform-material3" }
compose-multiplatform-material-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-material-icons-extended" }
compose-multiplatform-animation = { group = "org.jetbrains.compose.animation", name = "animation", version.ref = "compose-multiplatform" }
compose-multiplatform-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose-multiplatform" }
compose-multiplatform-foundation-layout = { group = "org.jetbrains.compose.foundation", name = "foundation-layout", version.ref = "compose-multiplatform" }
compose-multiplatform-material3-adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "compose-multiplatform-adaptive" }
compose-multiplatform-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-multiplatform-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
compose-multiplatform-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-multiplatform" }
compose-multiplatform-ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "compose-multiplatform" }
compose-multiplatform-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
compose-multiplatform-backhandler = { group = "org.jetbrains.compose.ui", name = "ui-backhandler", version.ref = "compose-multiplatform" }
compose-shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "compose-shimmer" }
compose-colorpicker = { group = "com.github.skydoves", name = "colorpicker-compose", version.ref = "compose-colorpicker" }
material-kolor = { group = "com.materialkolor", name = "material-kolor", version.ref = "materialkolor" }

compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

lifecycle-multiplatform-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle-multiplatform" }
lifecycle-multiplatform-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-multiplatform" }
lifecycle-multiplatform-viewmodel-navigation3 = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "lifecycle-multiplatform" }
lifecycle-multiplatform-runtime = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime", version.ref = "lifecycle-multiplatform" }
lifecycle-multiplatform-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-multiplatform" }

coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }

# Network & Serialization
ktor-client-core = { group = 'io.ktor', name = 'ktor-client-core', version.ref = 'ktor' }
ktor-client-android = { group = 'io.ktor', name = 'ktor-client-android', version.ref = 'ktor' }
ktor-client-darwin = { group = 'io.ktor', name = 'ktor-client-darwin', version.ref = 'ktor' }
ktor-client-logging = { group = 'io.ktor', name = 'ktor-client-logging', version.ref = 'ktor' }
ktor-client-mock = { group = 'io.ktor', name = 'ktor-client-mock', version.ref = 'ktor' }
ktor-client-content-negotiation = { group = 'io.ktor', name = 'ktor-client-content-negotiation', version.ref = 'ktor' }
ktor-serialization-kotlinx-json = { group = 'io.ktor', name = 'ktor-serialization-kotlinx-json', version.ref = 'ktor' }
kotlinx-serialization-json = { group = 'org.jetbrains.kotlinx', name = 'kotlinx-serialization-json', version.ref = 'kotlinx-serialization' }

# Depedency Injection
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-start-up = { group = "io.insert-koin", name = "koin-androidx-startup", version.ref = "koin" }

# Misc
napier = { group = "io.github.aakira", name = "napier", version.ref = "napier" }
android-youtube-player = { group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "core", version.ref = "android-youtube-player" }

# Firebase
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "crashlytics" }

# Database
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }
sqldelight-android = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-native = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }
sqldelight-driver = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqldelight" }

cryptography-core = { group = "dev.whyoleg.cryptography", name = "cryptography-core", version.ref = "cryptography" }
cryptography-ios = { group = "dev.whyoleg.cryptography", name = "cryptography-provider-cryptokit", version.ref = "cryptography" }

# Testing
androidx-test-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
screenshot-validation-api = { group = "com.android.tools.screenshot", name = "screenshot-validation-api", version.ref = "screenshot" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

# UI
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose-ui-test" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigation-compose" }
ui-automator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "ui-automator" }

# Mockers
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }

ktlint-cli = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint-cli" }

# Dependencies of the included build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "android-tools" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradle-plugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-multiplatform-gradle-plugin = { group = "org.jetbrains.compose", name = "org.jetbrains.compose.gradle.plugin", version.ref = "compose-multiplatform" }

[plugins]
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebase-appdistribution-gradle" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
screenshot = { id = "com.android.compose.screenshot", version.ref = "screenshot" }

#detekt-cli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt-cli" }
#detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt-cli" }

# Plugins defined by this project
divinelink-kotlin-multiplatform = { id = "com.divinelink.kotlin.multiplatform", version = "unspecified" }
divinelink-compose-multiplatform = { id = "com.divinelink.compose.multiplatform", version = "unspecified" }
divinelink-compose-feature = { id = "com.divinelink.compose.feature", version = "unspecified" }

divinelink-android-application = { id = "divinelink.android.application", version = "unspecified" }
divinelink-android-feature = { id = "divinelink.android.feature", version = "unspecified" }

