name: Build Signed Release APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_FILE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir -p "${TMP_KEYSTORE_FILE_PATH}"
          echo "$ENCODED_STRING" | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/keystore.jks

      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper
          key: gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-wrapper-

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/caches/modules-2/files-2.1
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-

      - name: Auth token to local.properties
        env:
          TMDB_AUTH_TOKEN: ${{ secrets.TMDB_AUTH_TOKEN }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
        run: |
          echo "TMDB_AUTH_TOKEN=${TMDB_AUTH_TOKEN}" >> local.properties
          echo "OMDB_API_KEY=${OMDB_API_KEY}" >> local.properties
          echo "TRAKT_API_KEY=dummy" >> local.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Signed Release APK
        run: ./gradlew :android:assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          TMDB_AUTH_TOKEN: ${{ secrets.TMDB_AUTH_TOKEN }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed
          path: android/build/outputs/apk/release/
